CREATE TABLE "Country" (
	"Id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"Name"	TEXT NOT NULL
)

CREATE TABLE "Authors" (
	"Id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"Name"	TEXT NOT NULL,
	"Surname"	TEXT NOT NULL,
	"CountryId"	INTEGER NOT NULL,
	FOREIGN KEY("CountryId") REFERENCES "Country"("Id")
)

CREATE TABLE "Books" (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"Title"	TEXT NOT NULL,
	"Date"	TEXT,
	"AuthorId"	INTEGER NOT NULL,
	FOREIGN KEY("AuthorId") REFERENCES "Authors"("Id")
)